Update v2_smartecolifeweb.yml

diff --git a/.github/workflows/v2_smartecolifeweb.yml b/.github/workflows/v2_smartecolifeweb.yml
--- a/.github/workflows/v2_smartecolifeweb.yml
+++ b/.github/workflows/v2_smartecolifeweb.yml
@@ -1,38 +1,43 @@
-# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
-# More GitHub Actions for Azure: https://github.com/Azure/actions
-
 name: Build and deploy Node.js app to Azure Web App - SmartEcolifeWeb
-
 on:
   push:
     branches:
       - V2
   workflow_dispatch:
-
 jobs:
   build:
     runs-on: windows-latest
-
     steps:
       - uses: actions/checkout@v4
-
       - name: Set up Node.js version
         uses: actions/setup-node@v3
         with:
           node-version: '20.x'
-
       - name: npm install, build, and test
         run: |
           npm install
           npm run build --if-present
           npm run test --if-present
+          
+      # Ensure index.html exists in the specified path
+      - name: Verify index.html exists in frontend-react/public
+        run: |
+          if [ ! -f "./frontend-react/public/index.html" ]; then
+            echo "index.html not found in ./frontend-react/public directory. Please ensure this file exists."
+            exit 1
+          fi
+
+      - name: Copy index.html to build directory
+        run: |
+          mkdir -p ./build/public
+          cp ./frontend-react/public/index.html ./build/public/index.html
       
       - name: Upload artifact for deployment job
         uses: actions/upload-artifact@v4
         with:
           name: node-app
-          path: .
-
+          path: ./build
+          
   deploy:
     runs-on: ubuntu-latest
     needs: build
@@ -40,8 +45,7 @@ jobs:
       name: 'Production'
       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
     permissions:
-      id-token: write #This is required for requesting the JWT
-
+      id-token: write # This is required for requesting the JWT
     steps:
       - name: Download artifact from build job
         uses: actions/download-artifact@v4
@@ -54,12 +58,11 @@ jobs:
           client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0B16C2ABEEA745DE9373FD64F5C6F0E1 }}
           tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B05CBA1F342C44598B0EEB5014049CA0 }}
           subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B20EEACC704B46BAA454837FFCEF8DD0 }}
-
+      
       - name: 'Deploy to Azure Web App'
         uses: azure/webapps-deploy@v3
         id: deploy-to-webapp
         with:
           app-name: 'SmartEcolifeWeb'
           slot-name: 'Production'
-          package: .
-          
+          package: ./build
